import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // BOOKS (5 products)
        {
            sellerId: 1,
            name: 'Introduction to Algorithms (CLRS)',
            description: 'Classic CS textbook, 3rd edition, like new condition',
            category: 'books',
            price: 60.00,
            imageUrl: 'https://placehold.co/400x400?text=Introduction+to+Algorithms',
            status: 'available',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 2,
            name: 'Calculus Early Transcendentals',
            description: "Stewart's Calculus 8th edition, good condition with some highlighting",
            category: 'books',
            price: 45.00,
            imageUrl: 'https://placehold.co/400x400?text=Calculus+Early+Transcendentals',
            status: 'sold',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            sellerId: 3,
            name: 'Physics for Scientists and Engineers',
            description: 'Serway & Jewett, 9th edition, minimal wear',
            category: 'books',
            price: 70.00,
            imageUrl: 'https://placehold.co/400x400?text=Physics+for+Scientists',
            status: 'available',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            sellerId: 1,
            name: 'Chemistry The Central Science',
            description: 'Brown LeMay 14th edition, includes access code',
            category: 'books',
            price: 55.00,
            imageUrl: 'https://placehold.co/400x400?text=Chemistry+Central+Science',
            status: 'available',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            sellerId: 4,
            name: 'Biology Campbell',
            description: 'Campbell Biology 11th edition, excellent condition',
            category: 'books',
            price: 80.00,
            imageUrl: 'https://placehold.co/400x400?text=Biology+Campbell',
            status: 'available',
            createdAt: new Date('2024-01-25').toISOString(),
        },
        // ELECTRONICS (5 products)
        {
            sellerId: 2,
            name: 'MacBook Pro 2020',
            description: '13-inch M1, 8GB RAM, 256GB SSD, great condition',
            category: 'electronics',
            price: 800.00,
            imageUrl: 'https://placehold.co/400x400?text=MacBook+Pro+2020',
            status: 'sold',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            sellerId: 3,
            name: 'iPad Air',
            description: '4th gen, 64GB, space gray, AppleCare until 2025',
            category: 'electronics',
            price: 400.00,
            imageUrl: 'https://placehold.co/400x400?text=iPad+Air',
            status: 'available',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            sellerId: 5,
            name: 'Mechanical Keyboard',
            description: 'Cherry MX Blue switches, RGB backlit',
            category: 'electronics',
            price: 85.00,
            imageUrl: 'https://placehold.co/400x400?text=Mechanical+Keyboard',
            status: 'available',
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            sellerId: 1,
            name: 'Noise Cancelling Headphones',
            description: 'Sony WH-1000XM4, barely used',
            category: 'electronics',
            price: 120.00,
            imageUrl: 'https://placehold.co/400x400?text=Noise+Cancelling+Headphones',
            status: 'available',
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            sellerId: 4,
            name: 'USB-C Hub',
            description: '7-in-1 adapter, HDMI, USB 3.0, SD card reader',
            category: 'electronics',
            price: 35.00,
            imageUrl: 'https://placehold.co/400x400?text=USB-C+Hub',
            status: 'available',
            createdAt: new Date('2024-02-07').toISOString(),
        },
        // STATIONERY (4 products)
        {
            sellerId: 2,
            name: 'Scientific Calculator',
            description: 'TI-84 Plus, works perfectly',
            category: 'stationery',
            price: 25.00,
            imageUrl: 'https://placehold.co/400x400?text=Scientific+Calculator',
            status: 'sold',
            createdAt: new Date('2024-02-09').toISOString(),
        },
        {
            sellerId: 3,
            name: 'Notebook Set',
            description: '5-pack Moleskine notebooks, various colors',
            category: 'stationery',
            price: 15.00,
            imageUrl: 'https://placehold.co/400x400?text=Notebook+Set',
            status: 'available',
            createdAt: new Date('2024-02-11').toISOString(),
        },
        {
            sellerId: 5,
            name: 'Fountain Pen',
            description: 'Pilot Metropolitan, includes converter and cartridges',
            category: 'stationery',
            price: 45.00,
            imageUrl: 'https://placehold.co/400x400?text=Fountain+Pen',
            status: 'available',
            createdAt: new Date('2024-02-13').toISOString(),
        },
        {
            sellerId: 1,
            name: 'Desk Organizer',
            description: 'Bamboo desk organizer with multiple compartments',
            category: 'stationery',
            price: 20.00,
            imageUrl: 'https://placehold.co/400x400?text=Desk+Organizer',
            status: 'available',
            createdAt: new Date('2024-02-15').toISOString(),
        },
        // FURNITURE (4 products)
        {
            sellerId: 4,
            name: 'Study Desk',
            description: 'IKEA standing desk, adjustable height, white',
            category: 'furniture',
            price: 120.00,
            imageUrl: 'https://placehold.co/400x400?text=Study+Desk',
            status: 'available',
            createdAt: new Date('2024-02-17').toISOString(),
        },
        {
            sellerId: 2,
            name: 'Office Chair',
            description: 'Herman Miller Aeron, used but excellent condition',
            category: 'furniture',
            price: 180.00,
            imageUrl: 'https://placehold.co/400x400?text=Office+Chair',
            status: 'sold',
            createdAt: new Date('2024-02-19').toISOString(),
        },
        {
            sellerId: 3,
            name: 'Bookshelf',
            description: '5-tier bookshelf, black, holds up to 50 books',
            category: 'furniture',
            price: 60.00,
            imageUrl: 'https://placehold.co/400x400?text=Bookshelf',
            status: 'available',
            createdAt: new Date('2024-02-21').toISOString(),
        },
        {
            sellerId: 5,
            name: 'Desk Lamp',
            description: 'LED desk lamp with USB charging port',
            category: 'furniture',
            price: 30.00,
            imageUrl: 'https://placehold.co/400x400?text=Desk+Lamp',
            status: 'available',
            createdAt: new Date('2024-02-23').toISOString(),
        },
        // CLOTHING (3 products)
        {
            sellerId: 1,
            name: 'College Hoodie',
            description: 'Official university hoodie, size M, navy blue',
            category: 'clothing',
            price: 35.00,
            imageUrl: 'https://placehold.co/400x400?text=College+Hoodie',
            status: 'available',
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            sellerId: 4,
            name: 'Winter Jacket',
            description: 'North Face puffer jacket, size L, black',
            category: 'clothing',
            price: 90.00,
            imageUrl: 'https://placehold.co/400x400?text=Winter+Jacket',
            status: 'sold',
            createdAt: new Date('2024-02-27').toISOString(),
        },
        {
            sellerId: 2,
            name: 'Backpack',
            description: 'SwissGear laptop backpack, fits 15-inch laptop',
            category: 'clothing',
            price: 55.00,
            imageUrl: 'https://placehold.co/400x400?text=Backpack',
            status: 'available',
            createdAt: new Date('2024-03-01').toISOString(),
        },
        // OTHER (2 products)
        {
            sellerId: 3,
            name: 'Mini Fridge',
            description: 'Compact dorm fridge, 1.7 cu ft, works great',
            category: 'other',
            price: 75.00,
            imageUrl: 'https://placehold.co/400x400?text=Mini+Fridge',
            status: 'available',
            createdAt: new Date('2024-03-03').toISOString(),
        },
        {
            sellerId: 5,
            name: 'Coffee Maker',
            description: 'Keurig K-Mini, single serve, includes pods',
            category: 'other',
            price: 25.00,
            imageUrl: 'https://placehold.co/400x400?text=Coffee+Maker',
            status: 'available',
            createdAt: new Date('2024-03-05').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 23 products created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});